@php
    $badgeColor = match($data['environment']) {
        'production' => '#dc2626',  // red
        'staging' => '#d97706',    // amber
        default => '#2563eb',      // blue
    };
@endphp

<div style="font-family: Arial, sans-serif; background: #f4f4f5; padding: 24px;">
    <div style="
        max-width: 720px;
        margin: 0 auto;
        background: #ffffff;
        border-radius: 8px;
        padding: 24px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.08);
    ">
        <!-- Header -->
        <div style="margin-bottom: 24px;">
            <h2 style="margin: 0 0 8px 0; font-size: 22px; color: #111827;">
                Application Exception Report
            </h2>

            <span style="
                display: inline-block;
                padding: 4px 10px;
                border-radius: 6px;
                font-size: 12px;
                background: {{ $badgeColor }};
                color: #fff;
                font-weight: bold;
                text-transform: uppercase;
            ">
                {{ $data['environment'] }}
            </span>

            <span style="
                display: inline-block;
                padding: 4px 10px;
                border-radius: 6px;
                font-size: 12px;
                background: #2563eb;
                color: #fff;
                font-weight: bold;
                text-transform: uppercase;
            ">
                #{{ $data['request_id'] }}
            </span>
        </div>

        <div style="margin-bottom: 24px;">
            <h3 style="margin-bottom: 12px; font-size: 18px; color: #1f2937;">Summary</h3>

            <div style="background: #f9fafb; padding: 16px; border-radius: 6px;">
                <p><strong>Message:</strong> {{ $data['message'] }}</p>
                <p><strong>Exception:</strong> {{ $data['message_short'] }}</p>
                <p><strong>Location:</strong> {{ $data['file'] }} : {{ $data['line'] }}</p>
                <p><strong>Timestamp:</strong> {{ $data['timestamp'] }}</p>
                @if($data['user'])
                    @if(is_array($data['user']))
                        <p><strong>User ID:</strong> {{ $data['user']['id'] }}</p>
                        <p><strong>User Email:</strong> {{ $data['user']['email'] }}</p>
                    @else
                        <p><strong>User ID:</strong> {{ $data['user'] }}</p>
                    @endif
                @endif
            </div>
        </div>

        <div style="margin-bottom: 24px;">
            <h3 style="margin-bottom: 12px; font-size: 18px; color: #1f2937;">Request Details</h3>

            <div style="background: #eef2ff; padding: 16px; border-radius: 6px;">
                <p><strong>Request ID:</strong> #{{ $data['request_id'] }}</p>
                <p><strong>URL:</strong> {{ $data['url'] }}</p>
                <p><strong>Method:</strong> {{ $data['method'] }}</p>
                <p><strong>IP Address:</strong> {{ $data['ip'] }}</p>
                <p><strong>User Agent:</strong></p>
                <pre style="
                    white-space: pre-wrap;
                    background: #e0e7ff;
                    padding: 12px;
                    border-radius: 6px;
                    font-size: 12px;
                ">{{ $data['user_agent'] }}</pre>
            </div>
        </div>

        <!-- Payload Section -->
        <div style="margin-bottom: 24px;">
            <h3 style="margin-bottom: 12px; font-size: 18px; color: #1f2937;">Payload</h3>

            <pre style="
                background: #fef3c7;
                white-space: pre-wrap;
                padding: 16px;
                border-radius: 6px;
                font-size: 12px;
                color: #92400e;
                overflow-x: auto;
            ">{{ json_encode($data['payload'], JSON_PRETTY_PRINT) }}</pre>
        </div>

        <!-- Stack Trace -->
        <div style="margin-bottom: 24px;">
            <h3 style="margin-bottom: 12px; font-size: 18px; color: #1f2937;">Stack Trace</h3>

            <pre style="
                background: #f3f4f6;
                color: #374151;
                padding: 16px;
                border-radius: 6px;
                font-size: 12px;
                white-space: pre-wrap;
                overflow-x: auto;
            ">{{ $data['trace'] }}</pre>
        </div>

        <p style="text-align: center; margin-top: 24px; font-size: 11px; color: #6b7280;">
            This is an automated error report generated by {{ config('app.name') }}.
        </p>
    </div>
</div>
